//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouthwestAutoCheckin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class CheckIn : global::System.Configuration.ApplicationSettingsBase {
        
        private static CheckIn defaultInstance = ((CheckIn)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CheckIn())));
        
        public static CheckIn Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.southwest.com/flight/retrieveCheckinDoc.html")]
        public string URL {
            get {
                return ((string)(this["URL"]));
            }
            set {
                this["URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("input#confirmationNumber")]
        public string ConfirmationNumberCss {
            get {
                return ((string)(this["ConfirmationNumberCss"]));
            }
            set {
                this["ConfirmationNumberCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("input#passengerFirstName")]
        public string ConfirmationFirstNameCss {
            get {
                return ((string)(this["ConfirmationFirstNameCss"]));
            }
            set {
                this["ConfirmationFirstNameCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("input#passengerLastName")]
        public string ConfirmationLastNameCss {
            get {
                return ((string)(this["ConfirmationLastNameCss"]));
            }
            set {
                this["ConfirmationLastNameCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button#form-mixin--submit-button")]
        public string ConfirmationSubmitButtonCss {
            get {
                return ((string)(this["ConfirmationSubmitButtonCss"]));
            }
            set {
                this["ConfirmationSubmitButtonCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.page-error")]
        public string ConfirmationErrorCss {
            get {
                return ((string)(this["ConfirmationErrorCss"]));
            }
            set {
                this["ConfirmationErrorCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button.boarding-pass-options--button-email")]
        public string SendToEmailButtonCss {
            get {
                return ((string)(this["SendToEmailButtonCss"]));
            }
            set {
                this["SendToEmailButtonCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button.form-mixin--submit-button")]
        public string EmailSubmitButton {
            get {
                return ((string)(this["EmailSubmitButton"]));
            }
            set {
                this["EmailSubmitButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button.boarding-pass-options--button-text")]
        public string SendToTextPhoneButtonCss {
            get {
                return ((string)(this["SendToTextPhoneButtonCss"]));
            }
            set {
                this["SendToTextPhoneButtonCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button.form-mixin--submit-button")]
        public string SendToTextPhoneSubmitButtonCss {
            get {
                return ((string)(this["SendToTextPhoneSubmitButtonCss"]));
            }
            set {
                this["SendToTextPhoneSubmitButtonCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("input#emailBoardingPass")]
        public string EmailAddressInputCss {
            get {
                return ((string)(this["EmailAddressInputCss"]));
            }
            set {
                this["EmailAddressInputCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div.overlay-background")]
        public string ChooseNextDeliveryMethodCss {
            get {
                return ((string)(this["ChooseNextDeliveryMethodCss"]));
            }
            set {
                this["ChooseNextDeliveryMethodCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("input#textBoardingPass")]
        public string TextPhoneInputCss {
            get {
                return ((string)(this["TextPhoneInputCss"]));
            }
            set {
                this["TextPhoneInputCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[data-a=\"airCheckInReviewResults_checkIn\"]")]
        public string ConfirmationSubmitButton2Css {
            get {
                return ((string)(this["ConfirmationSubmitButton2Css"]));
            }
            set {
                this["ConfirmationSubmitButton2Css"] = value;
            }
        }
    }
}
