//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouthwestAutoCheckin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class TestCheckIn : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestCheckIn defaultInstance = ((TestCheckIn)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestCheckIn())));
        
        public static TestCheckIn Default {
            get {
                return defaultInstance;
            }
        }
    }
}
